apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-node-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-node-demo
  template:
    metadata:
      labels:
        app: k3s-node-demo
    spec:
      containers:
        - name: tars
          image: docker.io/xiongsongsong/k3s-node-demo:1.0.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k3s-node-demo-service
  labels:
    app: k3s-node-demo-service
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 3010 # 宿主的端口
      protocol: TCP
      targetPort: 3000 # POD的端口
  selector:
    # 指定目标应用
    app: k3s-node-demo
  type: LoadBalancer
