apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 3010 # 宿主的端口
      protocol: TCP
      targetPort: 80 # POD的端口
  selector:
    # 指定目标应用
    app: nginx
  type: LoadBalancer
